services:
  puzzlelog-app:
    build: .
    container_name: puzzlelog-app
    restart: always
    ports:
      - "80:8080"  # 외부 80 포트 -> 컨테이너 내부 8080 포트
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}