version: '3.8'
services:
  app:
    build: .
    image: puzzlelog
    container_name: puzzlelog-app
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/puzzlelog_back/.env  # ✅ 수정된 위치
    ports:
      - "8080:8080"
