# ========== Application Name ==========
spring.application.name=puzzlelog

# ========== Server Configuration ==========
server.port=${SERVER_PORT:8080}

# ========== MySQL Configuration ==========
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== MongoDB URI ============
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# ========== JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ========== Logging Configuration ==========
logging.level.root=DEBUG
logging.level.org.springframework=INFO

# ========== No API Address Error ========
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# ========== File Upload Setting ========
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.mvc.contentnegotiation.favor-parameter=true
spring.mvc.contentnegotiation.parameter-name=mediaType